USE smart_waste;

-- Insert Multiple Zones (Ignore if duplicates)
INSERT IGNORE INTO zones (zone_id, zone_name, city, state) VALUES 
(2, 'North Zone', 'Chennai', 'Tamil Nadu'),
(3, 'South Zone', 'Chennai', 'Tamil Nadu'),
(4, 'East Zone', 'Chennai', 'Tamil Nadu'),
(5, 'West Zone', 'Chennai', 'Tamil Nadu');

-- 20 Waste Requests (COLLECTED status)
INSERT INTO waste_requests (user_id, collector_id, waste_type, weight_kg, status, zone_id, created_at, collected_time) VALUES
(11, 2, 'PLASTIC', 5.2, 'COLLECTED', 2, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
(11, 2, 'E_WASTE', 12.0, 'COLLECTED', 3, DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),
(11, 2, 'ORGANIC', 8.5, 'COLLECTED', 4, DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),
(11, 2, 'PAPER', 3.0, 'COLLECTED', 2, DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),
(11, 2, 'GLASS', 1.5, 'COLLECTED', 5, DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 19 DAY)),
(11, 2, 'PLASTIC', 4.1, 'COLLECTED', 3, DATE_SUB(NOW(), INTERVAL 22 DAY), DATE_SUB(NOW(), INTERVAL 21 DAY)),
(11, 2, 'E_WASTE', 25.0, 'COLLECTED', 4, DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 24 DAY)),
(11, 2, 'ORGANIC', 10.2, 'COLLECTED', 5, DATE_SUB(NOW(), INTERVAL 28 DAY), DATE_SUB(NOW(), INTERVAL 27 DAY)),
(11, 2, 'PAPER', 2.8, 'COLLECTED', 2, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),
(11, 2, 'GLASS', 6.0, 'COLLECTED', 3, DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),
(11, 2, 'PLASTIC', 3.3, 'COLLECTED', 4, DATE_SUB(NOW(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
(11, 2, 'E_WASTE', 18.5, 'COLLECTED', 5, DATE_SUB(NOW(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 13 DAY)),
(11, 2, 'ORGANIC', 7.7, 'COLLECTED', 2, DATE_SUB(NOW(), INTERVAL 17 DAY), DATE_SUB(NOW(), INTERVAL 16 DAY)),
(11, 2, 'PAPER', 4.4, 'COLLECTED', 3, DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 17 DAY)),
(11, 2, 'GLASS', 2.1, 'COLLECTED', 4, DATE_SUB(NOW(), INTERVAL 19 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY)),
(11, 2, 'PLASTIC', 9.0, 'COLLECTED', 5, DATE_SUB(NOW(), INTERVAL 21 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),
(11, 2, 'E_WASTE', 30.0, 'COLLECTED', 2, DATE_SUB(NOW(), INTERVAL 23 DAY), DATE_SUB(NOW(), INTERVAL 22 DAY)),
(11, 2, 'ORGANIC', 5.5, 'COLLECTED', 3, DATE_SUB(NOW(), INTERVAL 26 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY)),
(11, 2, 'PAPER', 1.8, 'COLLECTED', 4, DATE_SUB(NOW(), INTERVAL 27 DAY), DATE_SUB(NOW(), INTERVAL 26 DAY)),
(11, 2, 'GLASS', 4.0, 'COLLECTED', 5, DATE_SUB(NOW(), INTERVAL 29 DAY), DATE_SUB(NOW(), INTERVAL 28 DAY));

-- Insert ML Predictions for Zone vs Actual (using prediction_date in recent past)
INSERT INTO ml_predictions (zone_id, predicted_waste_kg, historical_waste_kg, day_of_week, month, year, prediction_date) VALUES
(2, 45.0, 40.0, 1, 5, 2026, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(3, 30.0, 25.0, 2, 5, 2026, DATE_SUB(NOW(), INTERVAL 9 DAY)),
(4, 55.0, 50.0, 3, 5, 2026, DATE_SUB(NOW(), INTERVAL 11 DAY)),
(5, 40.0, 38.0, 4, 5, 2026, DATE_SUB(NOW(), INTERVAL 19 DAY));

-- Insert Waste Logs (zone_id, waste_type, collected_weight_kg, collection_date)
INSERT INTO waste_logs (zone_id, waste_type, collected_weight_kg, collection_date) VALUES
(2, 'PLASTIC',  5.20, DATE_SUB(CURDATE(), INTERVAL 4 DAY)),
(3, 'E_WASTE',  12.00, DATE_SUB(CURDATE(), INTERVAL 9 DAY)),
(4, 'ORGANIC',  8.50, DATE_SUB(CURDATE(), INTERVAL 11 DAY)),
(2, 'PAPER',    3.00, DATE_SUB(CURDATE(), INTERVAL 14 DAY)),
(5, 'GLASS',    1.50, DATE_SUB(CURDATE(), INTERVAL 19 DAY)),
(3, 'PLASTIC',  4.10, DATE_SUB(CURDATE(), INTERVAL 21 DAY)),
(4, 'E_WASTE',  25.00, DATE_SUB(CURDATE(), INTERVAL 24 DAY)),
(5, 'ORGANIC',  10.20, DATE_SUB(CURDATE(), INTERVAL 27 DAY)),
(2, 'PAPER',    2.80, DATE_SUB(CURDATE(), INTERVAL 1 DAY)),
(3, 'GLASS',    6.00, DATE_SUB(CURDATE(), INTERVAL 7 DAY));
